from pathlib import Path
file1 = open("athletics3.txt", "w")
dates=Path('athletics2.txt').read_text()
dates=str(dates)
dates=dates.replace("[",'').strip()
dates=dates.replace("]",'').strip()
dates=dates.replace("'",'').strip()
dates=dates.replace('"','').strip()
dates=dates.replace(',',':').strip()
dates=dates.replace('01','1').strip()
dates=dates.replace('02','2').strip()
dates=dates.replace('03','3').strip()
dates=dates.replace('04','4').strip()
dates=dates.replace('05','5').strip()
dates=dates.replace('06','6').strip()
dates=dates.replace('07','7').strip()
dates=dates.replace('08','8').strip()
dates=dates.replace('09','9').strip()
file1.write(dates)
file1.close()

print(__file__) #print after program is run (for debugging in webmin)